### ISSUE TITLE
Production deployment checklist

### ISSUE THREAD

**Issue by henrytwo** [hack-the-6ix/api.hackthe6ix.com#34]
- [x] Setup Robo 3T
- [x] Setup the real email templates
- [x] Install Sentry for frontend
- [x] Install sentry for backend
- [x] Merge the develop branch on landing page to master
- [x] Purge databases
- [x] Purge keycloak accounts
- [x] Verify that domain whitelist is updated
- [x] Configure production confirmation and submission deadlines
- [x] Run stress test on production setup
- [x] Increase the lifetime on the application statistics to 1 hr
- [x] Update list of schools and stuff https://github.com/hack-the-6ix/hackthe6ix-admin-dashboard/blob/8cafb9d1315a34b7a434de6a2f9e17c033bed48b/src/utils/formEnums.js
